### ISSUE TITLE
Rollbar logger fails when app config is cached

### ISSUE THREAD

**Issue by wpearse** [rollbar/rollbar-php-laravel#100]
If you cache your Laravel config:

`php artisan config:cache`

You will stop receiving Rollbar logs in your dashboard, and you will see this error in your log files:

```
Unresolvable dependency resolving [Parameter #0 [ <required> array $config ]] in class Rollbar\RollbarLogger
```

This can be "solved" by un-caching your Laravel config (not really a solution):

`php artisan config:clear`

Seems similar to #64. I'm using rollbar/rollbar-laravel v6.0.0.

**Comment by danielmorell** [comment]
This should have been fixed in v4.0.1
