### ISSUE TITLE
Error when composer selects Monolog ^1 as a dependency

### ISSUE THREAD

**Issue by seb-jones** [rollbar/rollbar-php-laravel#101]
After upgrading from version 4.0.3 to version 5.0.0 we were getting an error like this on every request to our Laravel site:
```
[2020-08-10 11:28:23] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object](TypeError(code: 0): Argument 1 passed to Monolog\\Handler\\RollbarHandler::__construct() must be an instance of RollbarNotifier
```
It turned out that the problem was caused by another package that we had required with composer, which needed Monolog ^1.15. Since the `rollbar-php` package requires Monolog at `"^1 || ^2"`, it was allowing that, even though it seems that this package is not actually compatible with versions of Monolog before 2.0.0.

It may be helpful to explicitly require Monolog ^2 in this package.

**Comment by bishopb** [comment]
Thanks for the detailed analysis, and it does sound likely that pinning Monolog would help. However, given the age of the `v5` release of this library, and that contemporary Laravel now pins to Monolog 2, I think we may close this without a `v5.0.1` patch release.

If this does not seem reasonable, and a patch release for 5.0.1 is needed, please re-open the issue.
