### ISSUE TITLE
.env value expose in log

### ISSUE THREAD

**Issue by EvilTwin01** [rollbar/rollbar-php-laravel#111]
Rollbar capture all the .env value and display it inside the log. This lead to security concern. Is there any way to hide this? Issue found on laravel running on vapor.
![2021-05-31 01 46 33](https://user-images.githubusercontent.com/25205034/120159319-a86a8b80-c227-11eb-8e09-cdaad225ba34.jpg)

**Comment by bxsx** [comment]
Hi @EvilTwin01

Thanks for reporting and sorry for the confusion. You can use `scrub_fields` to remove any sensitive data. Please visit  https://docs.rollbar.com/docs/php-configuration-reference for more information.

If you want more control, you can also take an interest in the `transformer` class. Here is an example: https://github.com/rollbar/rollbar-php-examples/tree/master/transformer

Let me know if this works for you :)

**Comment by bxsx** [comment]
Closing the issue.

@EvilTwin01 please let me know if the proposed solution does not work for you, so I will reopen it.
Thanks
