### ISSUE TITLE
Create package for Laravel Nova

### ISSUE THREAD

**Issue by chrillep** [rollbar/rollbar-php-laravel#117]
How would one use this with Laravel Nova?

https://nova.laravel.com/docs/3.0/installation.html#error-reporting
https://github.com/rollbar/rollbar-php/issues/415

**Comment by bishopb** [comment]
Hello! Thanks for asking, @chrillep. The ideal way would be for us to provide a Nova-specific service provider and a simple set of instructions for activating that provider. That would be done under Issue #415. We are making a push right now on all Laravel derivatives, like Lumen and Zero, and I will press for a Nova integration as well.

Anyhow, in the meanwhile, you need a ServiceProvider with two methods: boot and register. The boot method will initialize Rollbar, via Rollbar::init() with your specific configuration. The register method will call Nova::report, and in the function that it takes, call Rollbar::logger()->log($exception).

Let me know if you need further details on that. Additionally, if you'd like to post a PR, those are welcome as well. I'm closing this for now, as the work to do it will be under Issue #415, but feel free to re-open to continue this conversation.

**Comment by bishopb** [comment]
Correction to my previous comment: I mistakenly thought Issue #415 was in this repo, it's not. This is the better repo for this conversation, so reopening and making this a feature request.
