### ISSUE TITLE
Update to rollbar-php 3.x

### ISSUE THREAD

**Issue by xtfer** [rollbar/rollbar-php-laravel#120]
I'm getting a persistent notice in rollbar about updating the library to rollbar-php 3.x. Will this project be getting an update or should I ignore it?

**Comment by jonnott** [comment]
I was thinking that package should also be prepared for the imminent release of Laravel 9.x. Maybe these could be rolled into a new major version release together. Both Laravel 9.x and rollbar-php 3.x require PHP 8.x.

Any word from the maintainers?

**Comment by nateiorg** [comment]
Any word? 

This isn't currently as benign as it may appear. The package requires:

```
"php": ">=7.2",
```

Yet, as of `8.1.0` many Rollbar classes are spamming instrumentation with deprecation warnings, and some classes are even outright failing to resolve as is being reported by Rollbar itself:

```
Error: Class "Rollbar\Payload\Person"
```

As one can imagine, with instrumentation being priced on rates, this can indeed be costing many people money (or resulting in throttling). If this package even limited PHP to a maximum of `8.0.x`, my deployments wouldn't have started using `8.1.x` for containers. That realistically _should_ be in place until `8.1.x` _is_ supported.

Can we please see an update here? I'm running Octane, which means I see a single bootstrap per deployment, but anyone who has a bootstrap per-request is going to be seeing tens of thousands of errors flooding instrumentation (or more). Even in my case, the flood of alerts post-deployment are obnoxious, and have already resulted in rate limiting.

I get that the deprecation warning is "just a warning", however, we run quite strict to combat accidental type coercion (and if I'm being honest, for _this_ exact scenario -- we absolutely don't want to be running deprecated code). If a company is forced to choose between using Rollbar and shifting their (arguably better) current paradigm to another (arguably worse) paradigm, Rollbar loses the battle every single time. It's really not even debatable whether we should start allowing/suppressing/ignoring warnings or not -- we won't.

**Comment by danielmorell** [comment]
Hey, I just want to jump on this issue and let everyone know that I am working on this and should have this ready soon.

**Comment by xtfer** [comment]
Thanks @danielmorell. Happy to be a test guinea pig if you need one/
