### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by whfamily2006** [rollbar/rollbar-php-laravel#13]
C:\xampp\htdocs\project> composer require rollbar/rollbar-laravel
Using version ^2.1 for rollbar/rollbar-laravel
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: rollbar/rollbar[v1.3.1, v0.18.2].
    - Can only install one of: rollbar/rollbar[v1.3.1, v0.18.2].
    - rollbar/rollbar-laravel v2.1.0 requires rollbar/rollbar ^1.3.1 -> satisfiable by rollbar/rollbar[v1.3.1].
    - Installation request for rollbar/rollbar-laravel ^2.1 -> satisfiable by rollbar/rollbar-laravel[v2.1.0].
    - Installation request for rollbar/rollbar (locked at v0.18.2) -> satisfiable by rollbar/rollbar[v0.18.2].

Installation failed, reverting ./composer.json to its original content.

**Comment by drbyte** [comment]
> - Installation request for rollbar/rollbar (locked at v0.18.2) -> satisfiable by rollbar/rollbar[v0.18.2].

That means your composer.json already contains "rollbar/rollbar: 0.18.2".

Simplest is likely to:
`composer remove rollbar/rollbar`
and then 
`composer require rollbar/rollbar-laravel`

(The rollbar/rollbar-laravel will automatically load the required rollbar/rollbar package, without you needing to have rollbar/rollbar in your composer.json file.)

**Comment by whfamily2006** [comment]
Thanks, @drbyte  actually I have installed `jenssegers` package `laravel-rollbar` and this package installed rollbar previous version. 
Thank again.

**Comment by drbyte** [comment]
Yes, uninstalling `jenssegers` package is required in order to use this one.
