### ISSUE TITLE
psr/log conflict

### ISSUE THREAD

**Issue by quantumwebco** [rollbar/rollbar-php-laravel#138]
This package is not installable in Laravel 9 without downgrading psr/log

I don't want to downgrade

Can rollbar be updated to be compatible with prs/log 3?

**Comment by adantart** [comment]
Any update here? So, Laravel 9 projects can't use Rollbar ?

**Comment by adantart** [comment]
@quantumwebco any other alternative to Rollbar ?
Sentry ? Raygun ? Instabug ?

**Comment by adantart** [comment]
@quantumwebco I've just tested Sentry and event it has some things better than Rollbar ... I can not wait for rollbar 4.0 to be released with no expectations :-)

**Comment by quantumwebco** [comment]
@adantart Sentry is nice but much more expensive and poor support. The free tier is also very restricting. I think rollbar is simpler and easier to use too. I would only use sentry if I was in a very big organisation

**Comment by danielmorell** [comment]
I don't know of any critical packages in the Laravel ecosystem that are not compatible with `psr/log` v2, but I might have missed some. We want to be careful to not make too many breaking changes if we can avoid it. But we are also sympathetic to being up to date with the latest versions.

We have a growing backlog of braking changes we need to make at some point. So `rollbar/rollbar` v4 will probably come sooner than later. I will have to talk to our product team, but we will probably try to set a date for the v4 release or at least a v4 beta.

**Comment by danielmorell** [comment]
Here is the `psr/log` v3 issue on the `rollbar/rollbar` package https://github.com/rollbar/rollbar-php/issues/570.

**Comment by danielmorell** [comment]
There is now an open PR for this https://github.com/rollbar/rollbar-php/pull/577. It will be released in v4.0.0.

**Comment by fbingha** [comment]
When is this v4.0.0 release coming out? I am evaluating replacing Bugsnag with Rollbar but this issue is having me considering not looking any further as it is concerning that you would let such a huge blocker fester for so long with Laravel 9. Laravel 9 was released almost a year ago.

**Comment by danielmorell** [comment]
@fbingha There are a few changes needed but we are hoping to get a beta out by the end of the year.

**Comment by nielsmouthaan** [comment]
I am also looking forward to 4.0.0 so I can use Rollbar in my Laravel 9 project.

**Comment by adantart** [comment]
@quantumwebco Totally agree, but I prefer to pay $20 or $40 and have something running in my Laravel 9 (a version that, as @fbingha said, it was released a year ago!), than to have NOTHING and waiting for "who knows when". Even @danielmorell said to have something for end of the (last) year, and we have no news.

It's not about who is better. It's about the information we have here officially.
If somebody would say "4.0 will be release 18th of Feb" we can decide which option take... but as far as we know now, Sentry at least has a Laravel 9 working solution.

**Comment by quantumwebco** [comment]
Well you can do that, no one is stopping you using Sentry or any other service. Personally I just downgraded psr/log to v2, it had no impact, everything works fine and as expected, and will upgrade again when v4 comes out. We're only 13 days in to the new year so I'm not freaking out that the release hasn't happened yet. I am using rollbar on the free tier and this package is open source and @danielmorell works hard on it to keep it maintained for us, so can't complain in the slightest that a non breaking downgrade is necessary to run this in L9. Personally I would ask @danielmorell if there is anything that needs doing and if I can help, happy to do some tasks and put in a PR

**Comment by adantart** [comment]
Sure @quantumwebco , please don't misunderstand me. He is doing a spectacular job, but the lack of information unfortunately makes us consider other solutions in the short term.

**Comment by danielmorell** [comment]
@adantart I completely understand your frustration. I would probably be frustrated too. So let me see if I can provide an update on where things are at.

There is one minor fix that is written but needs to be validated to ensure it does not cause issues with people using the Fluentd and agent transport methods. This fix is the last of the breaking changes. I should have it done by Monday. At that point it is just the process of getting the whole thing peer reviewed and published.

Also, thank you to you and @quantumwebco for the kind words!

**Comment by adantart** [comment]
@danielmorell ask for any help if needed

**Comment by danielmorell** [comment]
> @danielmorell ask for any help if needed

Thanks for the offer! This is the last issue I am working on https://github.com/rollbar/rollbar-php/issues/469. I am almost done with it.

**Comment by quantumwebco** [comment]
@danielmorell Likewise, just shout if/when there's any outstanding tasks I can help with

**Comment by danielmorell** [comment]
[rollbar/rollbar-php v4.0.0-beta](https://github.com/rollbar/rollbar-php/releases/tag/v4.0.0-beta) has been released.

**Comment by nielsmouthaan** [comment]
Thanks, @danielmorell. [Rollbar-php-laravel](https://github.com/rollbar/rollbar-php-laravel) likely also requires an update so it points to 4.0.0? Can you provide any pointers on how I can use [rollbar/rollbar-php v4.0.0-beta](https://github.com/rollbar/rollbar-php/releases/tag/v4.0.0-beta) in my Laravel project without using [rollbar-php-laravel](https://github.com/rollbar/rollbar-php-laravel) so I can test 4.0.0-beta?

**Comment by adantart** [comment]
> Thanks, @danielmorell. [Rollbar-php-laravel](https://github.com/rollbar/rollbar-php-laravel) likely also requires an update so it points to 4.0.0? Can you provide any pointers on how I can use [rollbar/rollbar-php v4.0.0-beta](https://github.com/rollbar/rollbar-php/releases/tag/v4.0.0-beta) in my Laravel project without using [rollbar-php-laravel](https://github.com/rollbar/rollbar-php-laravel) so I can test 4.0.0-beta?

Check this: https://github.com/rollbar/rollbar-php/discussions/597#discussioncomment-4744311

**Comment by danielmorell** [comment]
This was resolved in #142.
