### ISSUE TITLE
Please make a new release

### ISSUE THREAD

**Issue by boryn** [rollbar/rollbar-php-laravel#146]
Master is 19 commits ahead of 7.2.0

**Comment by boryn** [comment]
At Laravel 10, after running `composer require rollbar/rollbar-laravel`, it installs version 1.3.0 😵‍💫 

When trying to run `composer require rollbar/rollbar-laravel:dev-master` it says:

_Conclusion: don't install monolog/monolog 3.3.1 (conflict analysis result)_

I can see rollbar/rollbar 4.0 is not yet released as stable.

Eventually, I managed to install these packages by:

- lowering `"minimum-stability"` to `"rc"` in the `composer.json`
- running explicitly `composer require rollbar/rollbar:^4.0`
- running `composer require rollbar/rollbar-laravel:dev-master` but only after defining my own fork in `composer.json`

**Comment by cyrusradfar** [comment]
Thanks for the heads up. We will look into this update asap.

**Comment by mecca666** [comment]
Same issue after upgrading to Laravel 10. Thanks for the temp solution @boryn

**Comment by danielmorell** [comment]
Please set your `minimum-stability` to `rc` and require the latest `rollbar/rollbar-laravel:^8`. This will install the latest version `v8.0.0-RC1`.

If you have any feedback on how it works, please let us know. We want to address any issues it might have before releasing the stable version.
