### ISSUE TITLE
Hi, is there support for laravel 10?

### ISSUE THREAD

**Issue by feniksdv** [rollbar/rollbar-php-laravel#149]
`Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - illuminate/support[v6.0.0, ..., v6.19.1] require php ^7.2 -> your php version (8.1.5) does not satisfy that requirement.
    - illuminate/support[v7.0.0, ..., v7.28.4] require php ^7.2.5 -> your php version (8.1.5) does not satisfy that requirement.
    - illuminate/support[v8.0.0, ..., v8.11.2] require php ^7.3 -> your php version (8.1.5) does not satisfy that requirement.
    - digitallyhappy/assets 2.0.1 requires laravel/framework ^8.0 -> found laravel/framework[v8.0.0, ..., v8.83.27] but it conflicts with your root composer.json require (^10.0).
    - digitallyhappy/assets[2.0.2, ..., 2.0.4] require laravel/framework ^9.0|^8.0 -> found laravel/framework[v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.4] but it conflicts with your root composer.json require (^10.0).
    - rollbar/rollbar-laravel[v7.1.0, ..., v7.2.0] require illuminate/support ^6.0|^7.0|^8.0|^9.0 -> satisfiable by illuminate/support[v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.4].
    - rollbar/rollbar-laravel v7.0.0 requires illuminate/support ^6.0|^7.0|^8.0 -> satisfiable by illuminate/support[v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27].
    - Only one of these can be installed: illuminate/support[v5.0.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.4, v10.0.0, ..., v10.3.3], laravel/framework[v10.0.0, ..., v10.3.3]. laravel/framework replaces illuminate/support and thus cannot coexist with it.
    - digitallyhappy/assets 2.1.0 requires laravel/framework ^10|^9.0|^8.0 -> satisfiable by laravel/framework[v10.0.0, ..., v10.3.3].
    - Conclusion: don't install laravel/framework v10.0.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.0.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.0.3 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.1.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.1.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.1.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.1.3 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.1.4 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.1.5 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.2.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.3.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.3.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.3.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.3.3 (conflict analysis result)
    - Root composer.json requires rollbar/rollbar-laravel ^7 -> satisfiable by rollbar/rollbar-laravel[v7.0.0, v7.1.0, v7.2.0].
`

**Comment by danielmorell** [comment]
Try using [`v8.0.0-RC1`](https://github.com/rollbar/rollbar-php-laravel/releases/tag/v8.0.0-RC1).
