### ISSUE TITLE
JSON Body not sent to rollbar

### ISSUE THREAD

**Issue by magarrent** [rollbar/rollbar-php-laravel#155]
Hello there!

`"rollbar/rollbar-laravel": "^7.2",`

I don't see the JSON Body in any error in my rollbar, is this normal behavior? I just came from here: https://github.com/jenssegers/laravel-rollbar/issues/79

I'm missing any configuration or something. Thank you!

**Comment by danielmorell** [comment]
Thank you for reaching out Marc.

Could you clarify, just so I make sure I'm giving you the best help. Are you saying the JSON body of the HTTP request that is coming into your Laravel app?

 If that is your issue, make sure the `include_raw_request_body` config option is `true`. It defaults to `false`. There are some considerations when using this option. You can read more in our [Configuration Reference Docs](https://docs.rollbar.com/docs/php-configuration-reference).

**Comment by magarrent** [comment]
> Thank you for reaching out Marc.
> 
> Could you clarify, just so I make sure I'm giving you the best help. Are you saying the JSON body of the HTTP request that is coming into your Laravel app?
> 
> If that is your issue, make sure the `include_raw_request_body` config option is `true`. It defaults to `false`. There are some considerations when using this option. You can read more in our [Configuration Reference Docs](https://docs.rollbar.com/docs/php-configuration-reference).

Oou! Didn't know about this! I'll try it, thanks Daniel!

**Comment by danielmorell** [comment]
Hey Marc, I just want to circle back and check if that resolved the issue.

**Comment by magarrent** [comment]
> Hey Marc, I just want to circle back and check if that resolved the issue.

Hey Daniel! Yep sorry, it works now! Didn't know about that option,

Thank you!!
