### ISSUE TITLE
Don't report validation reported

### ISSUE THREAD

**Issue by whfamily2006** [rollbar/rollbar-php-laravel#16]
Here in my class `App\Exceptions\Handler`  validation exception included in $dontReport array `\Illuminate\Validation\ValidationException::class,`.
```
 protected $dontReport = [
        \Illuminate\Auth\AuthenticationException::class,
        \Illuminate\Auth\Access\AuthorizationException::class,
        \Symfony\Component\HttpKernel\Exception\HttpException::class,
        \Illuminate\Database\Eloquent\ModelNotFoundException::class,
        \Illuminate\Session\TokenMismatchException::class,
        \Illuminate\Validation\ValidationException::class,
    ];
```
but roll bar reported me. Is it correct behaviour..?
screen shot from rollbar.. 
![image](https://user-images.githubusercontent.com/9881496/30155997-d359036c-93d7-11e7-9a25-4a850fadf177.png)

**Comment by drbyte** [comment]
Please show your code for where you've enabled Rollbar in your application.

**Comment by whfamily2006** [comment]
@drbyte, I was just installed following the installation guide. 

In `AppServiceProvider`
```
public function register()
    {
		if ($this->app->environment('production')) {
			$this->app->register( \Rollbar\Laravel\RollbarServiceProvider::class );
		}
    }
```
In `config/services.php` and these both env variable declared in my environemnts files.
```
'rollbar' => [
		'access_token' => env('ROLLBAR_TOKEN'),
		'level' => env('ROLLBAR_LEVEL'),
	],
```
`report` method in `app/Exceptions/Handler.php`
```
 public function report(Exception $exception)
    {
	Log::error($exception);
        parent::report($exception);
    }
```

**Comment by drbyte** [comment]
Right. 

When you add `Log::error($exception);` to the `report()` method, it'll send everything to Rollbar, filtering only on "level", not exception-type.
You can skip that step if you prefer it to respect the $dontReport settings.

**Comment by ArturMoczulski** [comment]
@drbyte provided the correct solution here. I'm closing the issue.
