### ISSUE TITLE
Problem upgrading from v2.0 to v2.2

### ISSUE THREAD

**Issue by nateritter** [rollbar/rollbar-php-laravel#19]
I tried upgrading from v2.0 to v2.2 via composer but received the following error:
```
$ composer require rollbar/rollbar-laravel
Using version ^2.2 for rollbar/rollbar-laravel
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: rollbar/rollbar[v1.3.1, v1.0.1].
    - Can only install one of: rollbar/rollbar[v1.3.1, v1.0.1].
    - Can only install one of: rollbar/rollbar[v1.3.1, v1.0.1].
    - rollbar/rollbar-laravel v2.2.0 requires rollbar/rollbar ^1.3.1 -> satisfiable by rollbar/rollbar[v1.3.1].
    - Installation request for rollbar/rollbar-laravel ^2.2 -> satisfiable by rollbar/rollbar-laravel[v2.2.0].
    - Installation request for rollbar/rollbar (locked at v1.0.1) -> satisfiable by rollbar/rollbar[v1.0.1].


Installation failed, reverting ./composer.json to its original content.
```

So, I removed rollbar all together (and made sure I didn't have any other instances of rollbar, including old jenssegers packages installed) and reinstalled. That solved the issue.  Just wanted to post this in case there's someone else who needs the fix.

**Comment by ArturMoczulski** [comment]
Wasn't `composer update` working?

**Comment by drbyte** [comment]
This package won't install properly if that old unmaintained jenssegers package is already installed because the old one forces the incompatible v1.3.1 dependency.

**Comment by nateritter** [comment]
Composer update was not working. Same error as above. 

When I checked, I found I did not have the jeenssegers package installed.

**Comment by drbyte** [comment]
@nateritter You're right: when unable to resolve dependencies with competing packages, you need to remove the old ones first. Thanks for posting here for others' benefit.

Others had similar issue here: https://github.com/rollbar/rollbar-php-laravel/issues/13

I think this issue can be closed.
