### ISSUE TITLE
Composer can't find class

### ISSUE THREAD

**Issue by serg-mo** [rollbar/rollbar-php-laravel#21]
I did `composer install rollbar/rollbar-laravel` and added `Rollbar\Laravel\RollbarServiceProvider::class` to `config/app.php`. Composer downloaded all the dependencies, but the autoloader was not able to find the RollbarServiceProvider class.

The same steps work with `jenssegers/rollbar` and `Jenssegers\Rollbar\RollbarServiceProvider::class`.

**Comment by drbyte** [comment]
1. Did you first uninstall the jenssegers package, from Composer?
2. What version of Laravel?

**Comment by serg-mo** [comment]
- I installed the official package first, no prior rollbar
- 4.2

**Comment by drbyte** [comment]
hmmmm ... haven't used laravel 4.2 in ages ...

**Comment by jessewgibbs** [comment]
@serg-mo it looks like Laravel 4.2 is not actively supported by the maintainers.  5.1 appears to be the first version that has long-term support from the maintainers.

Is there any reason why you can't upgrade to a newer Laravel release?  I suspect that our dev team has only tested rollar-php-laravel w/ a 5+ version....

**Comment by drbyte** [comment]
@serg-mo ... Which PHP version?  
If you're using less than PHP 5.5, then the `::class` notation will not work, and you'll need to use the old syntax in your `app/config/app.php`:

```php
	'providers' => array(
//
            'Rollbar\Laravel\RollbarServiceProvider',
        ),
```

But there's a bug in this package that's been fixed, and until it's tagged, you're going to get Reflection errors.

**Comment by drbyte** [comment]
I just set up a fresh Laravel 4.2 app.
First, switched to PHP 5.6 (down from usual 7.2 I use in my dev env lately).
1. `composer create-project laravel/laravel new-42 "4.2.*"`
2. `cd new-42`
3. `composer require rollbar/rollbar-laravel`
4. Edit `config/app.php` and add to the `providers` array:
  `Rollbar\Laravel\RollbarServiceProvider::class,`
5. Edit `config/services.php` and add:
```php
'rollbar' => [
    'access_token' => 'my actual token here',
    'level' => 'debug',
],
```
6. Edit `routes.php`:
```diff
Route::get('/', function()
{
+    \Log::error('Test error');
	return View::make('hello');
});
```

Visit `/` in the browser. 
Get Reflection error.

Now run `composer require rollbar/rollbar-laravel:dev-master`
Now it works correctly: Rollbar gets the `Test` message, and no Reflection errors.

@serg-mo  can you or @ArturMoczulski  tag a new release so the bugfix in https://github.com/rollbar/rollbar-php-laravel/pull/18 is available for everyone?

**Comment by jessewgibbs** [comment]
@drbyte thanks for all the help with this!

**Comment by serg-mo** [comment]
I did all of that, but autoload_classmap.php still generates
```
'Jenssegers\\Rollbar\\Facades\\Rollbar' => $vendorDir . '/rollbar/rollbar-laravel/src/Facades/Rollbar.php',
    'Jenssegers\\Rollbar\\RollbarLogHandler' => $vendorDir . '/rollbar/rollbar-laravel/src/RollbarLogHandler.php',
    'Jenssegers\\Rollbar\\RollbarServiceProvider' => $vendorDir . '/rollbar/rollbar-laravel/src/RollbarServiceProvider.php',
```

**Comment by serg-mo** [comment]
maybe it has something to do with this

```
./vendor/rollbar/rollbar-laravel/composer.json:
    1  {
    2:     "name": "jenssegers/rollbar",
    3      "description": "Rollbar error monitoring integration for Laravel projects",
    4      "keywords": ["laravel", "rollbar", "monitoring", "error", "logging"],
    5:     "homepage": "https://github.com/jenssegers/laravel-rollbar",
    6      "license": "MIT",
    7      "authors": [
    8          {
    9              "name": "Jens Segers",
   10:             "homepage": "https://jenssegers.com"
   11          }
   12      ],
   ..
   24      "autoload": {
   25          "psr-4": {
   26:             "Jenssegers\\Rollbar\\": "src/"
   27          }
   28      }
```

**Comment by serg-mo** [comment]
I cleared composer cache and tried rollbar/rollbar:1.3.1 because dev-master requires it
but then I get this
```
Problem 1
    - Installation request for rollbar/rollbar-laravel dev-master -> satisfiable by rollbar/rollbar-laravel[dev-master].
    - rollbar/rollbar-laravel dev-master requires rollbar/rollbar ^1.3.1 -> satisfiable by rollbar/rollbar[v1.3.1, v1.3.2].
    - rollbar/rollbar v1.3.1 requires psr/log ~1.0.2 -> satisfiable by psr/log[1.0.2].
    - rollbar/rollbar v1.3.2 requires psr/log ~1.0.2 -> satisfiable by psr/log[1.0.2].
    - Conclusion: don't install psr/log 1.0.2
```

**Comment by drbyte** [comment]
From my fresh 4.2 install, as described above, here is my `composer.json`:

```json
{
	"name": "laravel/laravel",
	"description": "The Laravel Framework.",
	"keywords": ["framework", "laravel"],
	"license": "MIT",
	"type": "project",
	"require": {
		"laravel/framework": "4.2.*",
		"rollbar/rollbar-laravel": "2.2"
	},
	"autoload": {
		"classmap": [
			"app/commands",
			"app/controllers",
			"app/models",
			"app/database/migrations",
			"app/database/seeds",
			"app/tests/TestCase.php"
		]
	},
	"scripts": {
		"post-install-cmd": [
			"php artisan clear-compiled",
			"php artisan optimize"
		],
		"post-update-cmd": [
			"php artisan clear-compiled",
			"php artisan optimize"
		],
		"post-create-project-cmd": [
			"php artisan key:generate"
		]
	},
	"config": {
		"preferred-install": "dist"
	},
	"minimum-stability": "stable"
}
```

In what ways is yours different, and why?

Also, as was asked earlier, what's your reasoning behind using Laravel 4.2 ? And your PHP version?

**Comment by serg-mo** [comment]
Our legacy app uses Laravel 4.2 and there is a ton of code in it, so upgrading is not an option. I'll try "rollbar/rollbar-laravel": "2.2". Before I had "rollbar/rollbar-laravel": "*"

**Comment by serg-mo** [comment]
that was it, thanks guys

**Comment by drbyte** [comment]
Glad to help. 
You can close this issue.

**Comment by ArturMoczulski** [comment]
@serg-mo I just tested that
```json
"rollbar/rollbar-laravel": "*"
```
pulls `rollbar/rollbar-php-laravel:dev-master` and `rollbar/rollbar-php:v1.3.2` on which it depends.

Is that not what happens for you?

**Comment by serg-mo** [comment]
@ArturMoczulski yes, the install works fine, but for some reason the generated classmap is wrong.

**Comment by ArturMoczulski** [comment]
@serg-mo I see. What files is your composer dumping the autoload instructions? Mine uses `vendor/composer/autload_psr4.php`

```php
// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'phpDocumentor\\Reflection\\' => array($vendorDir . '/phpdocumentor/reflection-common/src', $vendorDir . '/phpdocumentor/type-resolver/src', $vendorDir . '/phpdocumentor/reflection-docblock/src'),
    'Webmozart\\Assert\\' => array($vendorDir . '/webmozart/assert/src'),
    'Symfony\\Component\\Yaml\\' => array($vendorDir . '/symfony/yaml'),
    'SampleRollbarPHP\\' => array($baseDir . '/src/SampleRollbarPHP'),
    'Rollbar\\Laravel\\' => array($vendorDir . '/rollbar/rollbar-laravel/src'),
    'Rollbar\\' => array($vendorDir . '/rollbar/rollbar/src'),
    'React\\Stream\\' => array($vendorDir . '/react/stream/src'),
    'React\\EventLoop\\' => array($vendorDir . '/react/event-loop/src'),
    'React\\ChildProcess\\' => array($vendorDir . '/react/child-process/src'),
    'Psr\\Log\\' => array($vendorDir . '/psr/log/Psr/Log'),
    'Monolog\\' => array($vendorDir . '/monolog/monolog/src/Monolog'),
    'Illuminate\\Support\\' => array($vendorDir . '/illuminate/support'),
    'Illuminate\\Contracts\\' => array($vendorDir . '/illuminate/contracts'),
    'Fluent\\Logger\\' => array($vendorDir . '/fluent/logger/src'),
    'Doctrine\\Instantiator\\' => array($vendorDir . '/doctrine/instantiator/src/Doctrine/Instantiator'),
);
```

What is the specific code your composer generates and in what file?

Also, @serg-mo, I really appreciate your input on this. Let's try to get this figured out fully.

**Comment by serg-mo** [comment]
@ArturMoczulski my current autoload_psr4.php contains the following
```
    'Rollbar\\Laravel\\' => array($vendorDir . '/rollbar/rollbar-laravel/src'),
    'Rollbar\\' => array($vendorDir . '/rollbar/rollbar/src'),
```
This is after I got it to work, the previous code snippet was from autoload_classmap.php when it was not working.

**Comment by raulidavid** [comment]
composer require rollbar/rollbar-laravel:master laravel 6????
