### ISSUE TITLE
Context Data

### ISSUE THREAD

**Issue by toddstoker** [rollbar/rollbar-php-laravel#22]
Context data doesn't seem to be working.

I've tried the following:
1. \Log::error($e, ['avar' => 'abcdef11']);
2. \Log::error($e, ['person' => ['avar' => 'abcdef11']]);

I see both exceptions are logged, but the context data is missing.

**Comment by ArturMoczulski** [comment]
@toddstoker Is there a reason why you closed this issue?

**Comment by toddstoker** [comment]
I'm no longer in a position to participate in resolving the issue (I'm not using Rollbar).
