### ISSUE TITLE
Disable Package Discovery

### ISSUE THREAD

**Issue by adriandmitroca** [rollbar/rollbar-php-laravel#24]
In my opinion, package discovery should not be supported in this package. Probably in 99% cases, Rollbar is not enabled on all environments but just for specified one, by registering Service Provider manually.

Currently, manual opting out in composer.json just for this specific package is required.

Reference: https://laravel.com/docs/5.5/packages#package-discovery

**Comment by drbyte** [comment]
Fair point, and doing that will save a CPU cycle by not having to check configuration.

However, the package will do nothing if it's not configured with Rollbar account credentials ... so if you're not deploying credentials to environments where you don't want Rollbar to fire, then there will be no undesired side-effects.

**Comment by ArturMoczulski** [comment]
I think it would be better to keep the package discovery by default as it makes the basic installation process easier and in line with many other Laravel packages. I will add to the README.md information on how to disable Rollbar package discovery in your Laravel project and why one would do it.

Consumers of Laravel package can disable Rollbar package discovery by using `dont-discover` option in their composer.json as instructed in https://laravel.com/docs/5.5/packages#package-discovery under section `Opting Out Of Package Discovery`.

What do you guys think?

**Comment by ArturMoczulski** [comment]
I'm going to close to this issue. If anybody wants to discuss this any further, I will reopen.

**Comment by ArturMoczulski** [comment]
This has been addressed in here: https://github.com/rollbar/rollbar-php-laravel/issues/30
