### ISSUE TITLE
Laravel v5.5 Traces Missing

### ISSUE THREAD

**Issue by paulrrogers** [rollbar/rollbar-php-laravel#25]
Exceptions appear as simple strings which lack traces when installed with Laravel 5.5

EDIT: Please see PR #26

**Comment by mitchjam** [comment]
I am also having this issue. I have just recently signed up for rollbar.

**Comment by ArturMoczulski** [comment]
This has been resolved in PR https://github.com/rollbar/rollbar-php-laravel/pull/26 which has been merged into master and will be included in tag 2.2.2
