### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by and-megan** [rollbar/rollbar-php-laravel#27]
Can we flesh out the readme and remove the screenshot?

**Comment by drbyte** [comment]
Please explain:
- what do `you` mean by `flesh out the readme`?
- why `remove the screenshot`?
- what's the reasoning behind these requests?

**Comment by and-megan** [comment]
* Flesh out the readme - a lot of the configuration options and methods from the php notifier can be added to this laravel readme: https://github.com/rollbar/rollbar-php. It'd be great to get some examples of use as well.

* remove the screenshot - this is an old screenshot of the Rollbar website & none of the other notifier libraries have a screenshot. 

* reasoning - improvement & uniformity with the other Rollbar libraries :) This readme is lacking in comparison.

**Comment by ArturMoczulski** [comment]
@and-megan I just did a bunch of improvements following the conventions from rollbar/rollbar-php. Can you check if you have any more suggestions?

Also, I'm going to create examples in rollbar/rollbar-php-examples and reference them in this readme as well. I don't really want to put examples in the repo that is being used in production by many.

**Comment by ArturMoczulski** [comment]
I added a Laravel example right here https://github.com/rollbar/rollbar-php-examples/tree/master/laravel/simple-logging
