### ISSUE TITLE
Dynamically Add global Context

### ISSUE THREAD

**Issue by michaelcurry** [rollbar/rollbar-php-laravel#28]
I am looking to add "global" context for logs in specific sections of the application.  For example, During a job, I would like to dynamically change the context of what entity is being worked on.  The context may change multiple timed within the same job.

```
Job Starts

foreach ($entities as $entity) {
Rollbar::setContext(['entity_id' => $entity->id]);

$entity->doSomething();
}

Job Ends
```

UPDATE: The main reason I need this is because we are logging warnings.  We need the context of the entity on the warning log.

**Comment by ArturMoczulski** [comment]
@michaelcurry Thanks for the feature request. It's actually something that will have to be implemented in https://github.com/rollbar/rollbar-php itself so I replicated this issue in that repo https://github.com/rollbar/rollbar-php/issues/285.

I will get to this as soon as I can.

**Comment by michaelcurry** [comment]
Sounds good @ArturMoczulski Do you have a rough timing estimate for this?

**Comment by ArturMoczulski** [comment]
@michaelcurry 

`RollbarLogger::addCustom`, `RollbarLogger::getCustom` and `RollbarLogger::removeCustom` have been added to `rollbar/rollbar-php`.

Here is an example of how to use it: https://github.com/rollbar/rollbar-php-examples/tree/master/laravel/custom-data

Tomorrow I will tag `rollbar/rollbar-php` so composer resolves dependencies with latest changes automatically. If you want to use it immediately, you will have to set the dependency on `rollbar/rollbar-php` to pull from master branch.

I will close the issue once I tag `rollbar/rollbar-php`.

**Comment by michaelcurry** [comment]
Awesome! I will wait till the tag it released. Thanks for jumping on this so quick :+1:

**Comment by ArturMoczulski** [comment]
Tag `1.3.4` is ready. Run `composer update` and `RollbarLogger::addCustom`, `RollbarLogger::removeCustom` and `RollbarLogger::getCustom` should be available.

Please check https://github.com/rollbar/rollbar-php-examples/tree/master/laravel/custom-data for examples of usage.

**Comment by michaelcurry** [comment]
@ArturMoczulski Funny enough I was going through the process of adding Dynamic Information for a `person` and found myself back in the same place I was in when creating this issue.  

The method of adding `custom` data does not use the same mechanism as adding `context` to a log.  This causes issues if someone wants to dynamically add in `person`, `session`, etc... data as a context OR simply want to `global add context to all Logs during an app session/job/etc...` to achieve the same result as having to add the `context` to each log individually.

For my specific issue, I was able to use the `Rollbar\RollbarLogger` Singleton, and force 'person_fn' into the config, but When dealing with other contexts, there are no "workarounds" to achieve the same result.  

The easiest way I can think of allowing Context to be added to the "global" Logger is to make addContext() public and not protected.  This should be a simple `rollbar-php-laravel` only change that would open up new possibilities.

Please let me know your team's thoughts on this and if you would like to discuss further, please let me know and we can figure out a way to get in touch.
