### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by KevinMarous** [rollbar/rollbar-php-laravel#35]
Hi there, we're trying  to install rollbar for Laravel, we've saw and follow the tutorial, composer install was succesfull (below require part of our composer.json)

`
"require": {
        "php": ">=7.1",
        "ext-gd": "*",
        "dimsav/laravel-translatable": "7.*",
        "doctrine/dbal": "^2.5",
        "fzaninotto/faker": "~1.4",
        "hyn/multi-tenant": " ^4.0@dev",
        "intervention/image": "^2.3",
        "laravel/framework": "5.4.*",
        "laravel/passport": "^3.0",
        "laravel/tinker": "~1.0",
        "league/flysystem-aws-s3-v3": "~1.0",
        "phpoffice/phpspreadsheet": "dev-develop",
        "predis/predis": "^1.1",
        "rollbar/rollbar": "^1.3",
        "rollbar/rollbar-laravel": "^2.2"
    },

`

The dashboard can catch our errors but this one is coming all the time : 

Symfony\Component\Debug\Exception\FatalThrowableError: Class 'Rollbar' not found

  The class already been created in our middleware folder .

Does someone have an idea ?

Thank you

**Comment by rivkahstandig3636** [comment]
Hi @KevinMarous, we'll take a look into this.

**Comment by ArturMoczulski** [comment]
@KevinMarous Thanks for bringing this up. I need to understand a bit more about the context of this error. Is there a trace? What part of the code is this being thrown in?

**Comment by ArturMoczulski** [comment]
@KevinMarous I'm going to close this issue for now. Will reopen when you get back with info I requested in the previous comment.
