### ISSUE TITLE
Truncate large payloads to ensure we don't drop them

### ISSUE THREAD

**Issue by rivkahstandig3636** [rollbar/rollbar-php-laravel#37]

**Comment by ArturMoczulski** [comment]
This is dependent on https://github.com/rollbar/rollbar-php/issues/329

That is, if there is anything to improve.

**Comment by vitxd** [comment]
Can you please upgrade the dependency of rollbar/rollbar-php so that it fixes this problem? Thanks :)

**Comment by denitsa-cm** [comment]
Also interested in this working. :)

**Comment by danielmorell** [comment]
This was fixed a long time ago.
