### ISSUE TITLE
Issues with config caching

### ISSUE THREAD

**Issue by rasmuscnielsen** [rollbar/rollbar-php-laravel#38]
When utilizing `php artisan config:cache` it seems that the service-provider stops itself from registering.

This behavior seems to be caused by `RollbarServiceProvider.php@stop` which has the following lines

```php
$level = getenv('ROLLBAR_LEVEL') ?: $this->app->config->get('services.rollbar.level', null);
$token = getenv('ROLLBAR_TOKEN') ?: $this->app->config->get('services.rollbar.access_token', null);
```  

A simple fix would be removing the `getenv()´ and rather rely on the config which would be the normal Laravel way of doing things.

**Comment by rivkahstandig3636** [comment]
Thanks for the bug report!

**Comment by ArturMoczulski** [comment]
@rasmuscnielsen What makes you think that the provider stops itself from running?

I can see that:
1. `Illuminate\Foundation\Console\ConfigClearCommand` just performs a delete on a file on the hard drive and doesn't initialize Laravel (and the `RollbarServiceProvider` with it).
2. `Illuminate\Foundation\Console\ConfigCachceCommand` initializes the Laravel framework and the `RollbarServiceProvider` is correctly initialized with it.

**Comment by rasmuscnielsen** [comment]
@ArturMoczulski 

After further debugging I realize now that I had named my config `services.rollbar.token` instead of `services.rollbar.access_token`.
The issue was only apparent when caching config, as `getenv()` always returns `false` when config is cached.

That caused it to stop the registration in production.

Thanks for the quick response

**Comment by gavinr** [comment]
I am getting this issue still. When I run `php artisan config:cache` rollbar reports stop working. When I run `php artisan config:clear` they work fine.

## Versions

`laravel/framework`: `v5.5.34
`rollbar/rollbar-php`: `v1.5.3`
`rollbar/rollbar-laravel`: `v2.3.0`

**Comment by rasmuscnielsen** [comment]
@gavinr for me it turned out to be an issue with my own setup. 
What does your config/services.php file look like (just the rollbar specific section)?

**Comment by gavinr** [comment]
@rasmuscnielsen Thanks for the response. I do not have any rollbar settings in `config/services.php` - is this my problem?

**Comment by rasmuscnielsen** [comment]
@gavinr Yep. When using config cache, getenv will stop working and Rollbar will try to read from the services.php instead.

Try and add this to your config/services.php

 'rollbar' => [
    'access_token' => env('ROLLBAR_TOKEN'),
    'level' => env('ROLLBAR_LEVEL'),
],

**Comment by gavinr** [comment]
@rasmuscnielsen that worked. Thanks. Although the documentation does mention this change, FWIW I think it should be more clearly marked as required, as I read over it but assumed it was optional based on the wording. Thanks!
