### ISSUE TITLE
Trouble Setting Up

### ISSUE THREAD

**Issue by ajtran** [rollbar/rollbar-php-laravel#40]
User is using PHP 5.6 and has followed the set up on the onboarding page:

`composer require rollbar/rollbar-laravel`

`ROLLBAR_TOKEN="ACCESS_TOKEN"`

and turned off auto-discovery, but is unable to send data to Rollbar with this line:

`\Log::debug('Test debug message');`

internal:https://app.intercom.io/a/apps/rlisg82q/inbox/inbox/849049/conversations/15697158706

**Comment by JeremyHargis** [comment]
I can't access your link, but I think I'm seeing the same problem. It works fine in my dev environment (Ubuntu 18.04, PHP 7.2.3), but in production (Windows Server 2012 R2, PHP 7.1.10) errors aren't making it to Rollbar. Things I've tried:

- Connectivity from the Windows server: I am able to get a “pong” back from a curl ping to the Rollbar API URL (I did also confirm neither the local software firewall nor the Azure network firewall was stopping the traffic)
- Made sure all composer packages have latest minor patches
- Rebuilt composer autoload
- Made sure old Laravel config wasn’t cached
- Matched the Rollbar config parameters with those in my development environment
- Tried with and without Laravel’s package auto-discovery feature
- Tried setting the ROLLBAR_LEVEL parameter to debug to make sure nothing was being stopped there

**Comment by BreezeRay** [comment]
Hello,  have been advised to comment here as I have had the same issues as above.  Everything works fine in the local set up but it failes to send messages from within a Windows Server set up.   Have tried many of the same things to resolve as above but nothing works.  No errors at all, but the test message never gets fired.

**Comment by ArturMoczulski** [comment]
This might get resolved by fixing the library for Windows environments. I will update the thread once that's resolved.

**Comment by ArturMoczulski** [comment]
I believe this is due to lack of the appropriate path for SSL certs on Windows Server machines. I just added logging of connectivity errors with Rollbar API to the extension.

@BreezeRay or @JeremyHargis , can use the latest code from branch `laravel-5.5` and check your Laravel log to see the error message. My guess is that you will be getting: `SSL certificate problem: unable to get local issuer certificate`. Can you check this for me?

**Comment by JeremyHargis** [comment]
I've since moved to a different error reporting service, so I will likely not have time to test this any time soon. Sorry about that.

**Comment by ArturMoczulski** [comment]
I'm closing the issue until further feedback.

**Comment by BreezeRay** [comment]
I no longer use the software - following poor responses and software that just does not work I use a different provider that worked first time without any issues.

**Comment by eightsixeight** [comment]
> I believe this is due to lack of the appropriate path for SSL certs on Windows Server machines. I just added logging of connectivity errors with Rollbar API to the extension.
> 
> @BreezeRay or @JeremyHargis , can you use the latest code from branch `laravel-5.5` and check your Laravel log to see the error message. My guess is that you will be getting: `SSL certificate problem: unable to get local issuer certificate`. Can you check this for me?

this is what im getting as well, we have deep packet inspection firewall, anyway to not use ssl check ?
