### ISSUE TITLE
Variable errors in views are not reporting

### ISSUE THREAD

**Issue by ahinkle** [rollbar/rollbar-php-laravel#41]
Bug i've noticed in the past month or so. When there is a variable that doesn't exist in a view, it appears in the error log but is not reporting to Rollbar. Previously, it would report these types of issues.

- Laravel Error Log:
![screen shot 2018-04-24 at 7 46 50 pm](https://user-images.githubusercontent.com/17038330/39220696-4dbd06d8-47f8-11e8-9513-89ff9324ce44.png)

- Rollbar:
![screen shot 2018-04-24 at 7 48 10 pm](https://user-images.githubusercontent.com/17038330/39220714-779d62a4-47f8-11e8-983c-55920dbe28a6.png)

**Comment by rivkahstandig3636** [comment]
Hi @ahinkle, I'm not sure what you mean it isn't reporting to Rollbar. Your screenshot shows it in Rollbar. Can you explain a bit more?

**Comment by ahinkle** [comment]
Sorry, I just noticed how my screenshots looks like they are together. However these are two separate screenshots - one from my error log (in Laravel) the other is the error log on Rollbar.  I've modified my original post to reflect this. Thanks!

**Comment by rivkahstandig3636** [comment]
I see. So to clarify, these sorts of errors aren't being reported to us?

**Comment by ahinkle** [comment]
Yes, so if I have a collection with a relationship:
`$users = Users::with('Permissions')->get();`

and I pass that collection to the view. Then I call something within a collection on a relationship that doesn't exist such as:
```
foreach ($users as $user) {
<p> {{ $user->Permissions->foo }} </p>
}
```

It will return the error:
`trying to get property of 'foo' of non-object`

Obviously, this is an error from the application that we need to fix but we are unable to discover such error without directly looking in the error log since it does not report to Rollbar.

**Comment by rivkahstandig3636** [comment]
Is this a handled or unhandled error?

**Comment by ahinkle** [comment]
Unhandled error. This is the default PHP notice `Trying to get property of non-object`.
Relating PHP Error: http://php.net/manual/en/function.isset.php#86313

**Comment by rivkahstandig3636** [comment]
Okay got it, thanks! We'll take a look into this.

**Comment by ArturMoczulski** [comment]
@ahinkle @marius-c I've been trying to reproduce the problem, but I don't seem to be able to

Can you update the SDK to the latest version (I assume you're on Laravel <= `5.5` so update to the latest `v2.*` release) and check if you're still having these problems?

Also, can you provide more information on how you're configuring the SDK, especially the error levels?

**Comment by ahinkle** [comment]
I can confirm that this has been fixed. Sorry I should have closed sooner. Maybe within a recent release or the API itself?
