### ISSUE TITLE
Add code_version config option

### ISSUE THREAD

**Issue by rivkahstandig3636** [rollbar/rollbar-php-laravel#43]
Similar to code_version in rollbar-php

**Comment by ArturMoczulski** [comment]
This is already supported. All needs to be done is add `code_version` config option to the configuration.

For Laravel <= `5.5` add the following to `config/services.php`:

```php
'rollbar' => [
            ...
            'code_version' => 'foo'
        ]
```

For Laravel >= `5.6`, add the following to `config/logging.php`:

```php
'rollbar' => [
            'driver' => 'monolog',
            'handler' => \Rollbar\Laravel\MonologHandler::class,
            'access_token' => ...,
            ...,
            'code_version' => 'foo'
        ]
```
