### ISSUE TITLE
Failed to connect on local environment.

### ISSUE THREAD

**Issue by brneas** [rollbar/rollbar-php-laravel#51]
Rollbar is unable to connect to the api on my local environment.

On my local environment when I `dd(Rollbar::info("Some info"));` in RollbarServiceProvider.php I get the response:
`Response {#318 ▼
  -status: 0
  -info: "Failed to connect to api.rollbar.com port 443: Connection refused"
  -uuid: "REDACTED"
} `

I am using Laravel Valet and am using a secure valet "domain."

I am also able to ping api.rollbar.com perfectly fine.

**Comment by ArturMoczulski** [comment]
@brneas I believe this would be some complication with an SSH connection from inside Valet. Can you try to test your connection in a different environment that isn't a local machine?

**Comment by jessewgibbs** [comment]
I'm closing this since the reporter hasn't responded.
