### ISSUE TITLE
[fork] support for laravel 5.6

### ISSUE THREAD

**Issue by andrewmclagan** [rollbar/rollbar-php-laravel#53]
Whilst awaiting the maintainers to accept our PR or write in support fo Laravel 5.6 please use `ethical-jobs/rollbar-php-laravel` via composer or github

https://github.com/ethical-jobs/rollbar-php-laravel

https://packagist.org/packages/ethical-jobs/rollbar-laravel

PR: https://github.com/rollbar/rollbar-php-laravel/pull/52

This requires php `v7.1.x` as per Laravel `v5.6.x`

**Comment by andrewmclagan** [comment]
Thanks! 

Copying you in on this @ig

**Comment by ArturMoczulski** [comment]
This has been merged into `master` which will now be the Laravel 5.6 support line along with 3.x.x releases. We will still maintain support for Laravel 5.5 and below in the `laravel-5.5` branch and in the 2.x.x releases.

**Comment by ArturMoczulski** [comment]
@andrewmclagan if you wish, further work on 3.x.x releases can be done in the `master` branch instead of the ethical-jobs fork
