### ISSUE TITLE
Wrong package name breaks satis mirror

### ISSUE THREAD

**Issue by olafnorge** [rollbar/rollbar-php-laravel#61]
A change in https://github.com/rollbar/rollbar-php-laravel/pull/52 breaks satis mirrors because they can't find the package by name on github anymore.

Relevant line in composer.json is: https://github.com/rollbar/rollbar-php-laravel/blob/294d3ae8cd9cb06f8d893b198c655784c413e081/composer.json#L2

May you be so kind and fix it. :)

**Comment by jessewgibbs** [comment]
@olafnorge thanks for bringing this to our attention.  The maintainer will investigate this soon.

**Comment by ArturMoczulski** [comment]
Fixed in `master` and will be released in `v4.0.2`

@olafnorge thx for bringing this up
