### ISSUE TITLE
Laravel v5.3.31 works with rollbar-php-laravel v2.3

### ISSUE THREAD

**Issue by ajtran** [rollbar/rollbar-php-laravel#63]
internal: https://app.intercom.io/a/apps/rlisg82q/inbox/inbox/488687/conversations/18398604002

Can Laravel v5.3.31 work with more recent versions of rollbar-php-laravel?

**Comment by ArturMoczulski** [comment]
@ajtran Laravel `v5.3.31` will work with `v2.*` line of SDK releases

`v2.*` releases support Laravel <= `5.5`
`v4.*` realeses support Laravel >= `5.6`

I maintain both release lines with up to date improvements and bug fixes as much as I can.
