### ISSUE TITLE
[4.0.1] Rollbar not reporting for Laravel <= 5.5

### ISSUE THREAD

**Issue by patrickcarlohickman** [rollbar/rollbar-php-laravel#66]
In v3.0.4, the `RollbarServiceProvider` sets up an event listener on Laravel's logger to handle sending the log message on to Rollbar.

In v4.0.0, this event listener was removed, and instead the `RollbarServiceProvider` binds a new custom exception handler over Laravel's default one, and this custom exception handler is responsible for sending the log message on to Rollbar.

In v4.0.1, this custom exception handler was removed, but the event listener from v3.0.4 was not added back in, so I believe that right now, there is nothing in Laravel <= 5.5 that sends the log message on to Rollbar.

Laravel >= 5.6 still works since the `rollbar` channel that is setup reports the log message directly to Rollbar.

I would suggest bringing the event listener back, but I believe you'll also need to include a check on Laravel <= 5.5 vs Laravel >= 5.6, since I think the messages would get duplicated in >= 5.6.

Thanks,
Patrick

**Comment by jessewgibbs** [comment]
Thanks for the detailed report, @patrickcarlohickman.  We'll investigate this soon and follow-up with you if we need more information.

**Comment by ArturMoczulski** [comment]
@patrickcarlohickman for Laravel <= 5.5 you should be using the `v3.*` line of releases. Not `v4.*`.

So if you're using Laravel <= 5.5 please use the latest appropriate release, which is `v3.0.4`.

All the essential changes are reproduced among both release lines as much as possible.
