### ISSUE TITLE
"Unable to send messages to Rollbar API. Produced response:" message after every log item

### ISSUE THREAD

**Issue by szekeresa** [rollbar/rollbar-php-laravel#70]
Hi!

I use Laravel 5.1 and rollbar-php-laravel v2.4.1.

"prod.ERROR: Unable to send messages to Rollbar API. Produced response:" message after every log item...
No response text, only this message.

I use other Laravel 5.1 project and rollbar-php-laravel v2.3.0 but no problem, only v2.4.1.

**Comment by jessewgibbs** [comment]
@szekeresa sorry to hear that you're encountering this issue.  We'll have one of our PHP maintainers take a look at this.

**Comment by ArturMoczulski** [comment]
@szekeresa thanks for reporting. I was trying to reproduce the problem on Laravel 5.1 and rollbar-php-laravel v2.4.1 but no luck.

Can you tell me more about how your SDK is configured and what exactly are you trying to report?

**Comment by jessewgibbs** [comment]
Closing this issue since there's been no response from the reporter.

**Comment by szekeresa** [comment]
Sorry for the late answer!

If "**ROLLBAR_LEVEL=error**" defined is .env AND run `Log::error("test")` is OK.
If run `Log::info("test")` then in logfile:
`local.ERROR: Unable to send messages to Rollbar API. Produced response:`

If "**ROLLBAR_LEVEL**" not defined in .env then `Log::error("test")` and `Log::info("test")` is OK!
