### ISSUE TITLE
RollbarServiceProvider won't log errors returned by api. 

### ISSUE THREAD

**Issue by Ramapitecus** [rollbar/rollbar-php-laravel#74]
On this line: `if (!$result || !$result->getStatus()) {` `getStatus()` returns the http reponse status returned by the api, which is a number and will be true. So, even when the API returns an error status >= 400 no message will be logged.

**Comment by jessewgibbs** [comment]
@ramapitecus thanks for bringing this to our attention.

@ArturMoczulski can you take a look into this?

**Comment by ArturMoczulski** [comment]
Fixed in branch `laravel-5.5` and will be included in the next `v3.*`-line release. The bug doesn't exist in `master`. Thanks @Ramapitecus
