### ISSUE TITLE
Incompatible with monolog/monolog ^2, (which Laravel 6 uses by default)

### ISSUE THREAD

**Issue by vadremix** [rollbar/rollbar-php-laravel#88]
Tested c6786393 and ran into this:

```
PHP Fatal error:  Declaration of Rollbar\Monolog\Handler\RollbarHandler::write(array $record) must be compatible with Monolog\Handler\AbstractProcessingHandler::write(array $record): void in [project-dir]/vendor/rollbar/rollbar/src/Monolog/Handler/RollbarHandler.php on line 55
```

Laravel 6 still supports monolog/monolog 1.x, so by putting a version constraint in composer.json I was able to identify that this is due to a breaking change with 2.x

**Comment by jonnott** [comment]
Yes, this has already come up ... you can make all the composer dependencies resolve only if you pin the monolog version in your whole Laravel project back to ^1.0 .. which sucks if you have something else in your project that needs monolog ^2.0.

**Comment by ArturMoczulski** [comment]
Should be resolved in https://github.com/rollbar/rollbar-php-laravel/releases/tag/v5.0.0

Please let me know if you run into any problems
