### ISSUE TITLE
Unable to create configured logger

### ISSUE THREAD

**Issue by Mattnmoore** [rollbar/rollbar-php-laravel#93]
After upgrading to Laravel 6.*, I've encountered an error while trying to use Rollbar.

```
Unable to create configured logger. Using emergency logger. {"exception":"[object] (TypeError(code: 0): Argument 1 passed to Monolog\\Handler\\RollbarHandler::__construct() must be an instance of RollbarNotifier, instance of Rollbar\\RollbarLogger given, called in /vagrant/api/vendor/rollbar/rollbar-laravel/src/RollbarServiceProvider.php on line 54 at /vagrant/api/vendor/monolog/monolog/src/Monolog/Handler/RollbarHandler.php:68)
```

I'm on the `dev-master` branch of `rollbar/rollbar-laravel` and the following is my config.

```
        'rollbar' => [
            'driver' => 'monolog',
            'handler' => \Rollbar\Laravel\MonologHandler::class,
            'access_token' => env('ROLLBAR_TOKEN'),
            'level' => env('ROLLBAR_LEVEL')
        ]
```

Any help would be appreciated.

**Comment by Mattnmoore** [comment]
It looks like `MonologHandler.php` might be extending the wrong class...If you replace` Monolog\Handler\RollbarHandler` with `Rollbar\Monolog\Handler\RollbarHandler` it seems to correct the issue.

**Comment by letaniaferreira** [comment]
related issue https://github.com/rollbar/rollbar-php/issues/249

**Comment by bxsx** [comment]
Related issue: https://github.com/rollbar/rollbar-php-symfony-bundle/pull/63/

**Comment by danielmorell** [comment]
The correct handler should be `Monolog\Handler\RollbarHandler`.
