### ISSUE TITLE
Preparedness for Laravel 7.x

### ISSUE THREAD

**Issue by jonnott** [rollbar/rollbar-php-laravel#96]
Laravel 7 will be released during Feb 2020.

This lib should be preparing for that by looking to depend on illuminate/support ^7.0 as well as ^6.0. Changes to that dependency are unlikely to bring many BC-breaks, if any (obviously this won't be known for definite until L7.0 is available).

Could potentially just be a minor 5.0.1 release of this lib to add illuminate/support ^6.0|^7.0 ?

When L6.0 was release, we had to wait a seriously long time for this lib to support it, so would be good to be on the front-foot with it this time around, now Laravel has switched to semantic versioning and therefore 6-monthly major version number increments.

**Comment by dinandmentink** [comment]
Tried updating to L7 this morning, ran into rollbar like I ran into it for L6.

**Comment by waltjones** [comment]
https://github.com/rollbar/rollbar-php-laravel/pull/97 should support Laravel 7. If there is still an issue, please reopen with details.
